# Site settings
title: The Onj: Software Consulting
email: angelahontau@gmail.com
description: |
  Software consulting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://theonj.com" # the base hostname & protocol for your site
twitter_username: theonj
github_username:  Krincle

# Build settings
markdown: kramdown
